### ISSUE TITLE
Question: is there any go-sdk about creating OpenShift cluster on IBM Cloud

### ISSUE THREAD

**Issue by liyanwei93** [IBM/ibm-cloud-sdk-common#29]
Hi team, Is there any go-sdk about creating/updating/deleting OpenShift cluster on IBM Cloud ?

**Comment by Andras-Csanyi** [comment]
I believe [this](https://docs.openshift.com/container-platform/4.7/operators/operator_sdk/golang/osdk-golang-quickstart.html) is something you are looking for. It is published and maintained by Red Hat.
