### ISSUE TITLE
PostChanges()  timeout  not  occur 

### ISSUE THREAD

**Issue by groezing** [IBM/ibm-cloud-sdk-common#49]
postChanges()  call does never return, seems to hang forever  even the timeout duration is reached. 

I have following function in my  client code to run  postChanges() in an endless loop 
```

function setupFollow(seq) {
 try {   
     db.postChanges({"db":self.databaseName  "feed":"longpoll","timeout": 60000,"since": seq,"includeDocs" : true })
     .then(response => {
          logger.info(method,  numOfChangesDetected + " changes records received from configDB with last seq : ", lastSeq);
          ........
          setupFollow(lastSeq) 
     .catch( (err) => {
                logger.error(method, "Failed to read trigger config info in configDB with  error : ",err);
                //** Continue to try to read from configDB after a retry wait time  with initial seq_nr  	
                setTimeout( () => {setupFollow( seq );}, retryDelay );	 
                logger.error(method, ": Error while read on provider DB : " + err , "will retry to read in ", retryDelay, " seconds");
     })
 } catch (err) {
    logger.error(method, ": Error in setting up change listener on provider DB : " + err , "will retry to read in 3 seconds");
    //** Continue to try to read from configDB after a retry wait time  with initial seq_nr   
    setTimeout( () => {setupFollow( seq );}, 1000 );	
 }
}

```

Error situation:  The logs over days show, that the setupFollow() is called in a loop. But then it  stopped  at one single call: 
     logline:  
`Dec 18 12:06:15 alarmstrigger-01-worker-76f44f7cc9-4dllr alarmstrigger-01-worker INFO [??] [alarmsTrigger] [setupFollow] Next trigger configDB read sequence starts on : [ 1520029-g1AAAAObeJzLYWBg4MhgTmFQTklKzi9KdUhJMtZLytUtz8gszjYwNNJLzskvTUnMK9HLSy3JASpmSmRIkv___39WBnMSA9Mjs1ygGHtqWpKhaXIycaaQZFuSApBMsodbeF8bbKGZgVlKmoUJLSx0AFkYD7fwwzqwhRYmhmkWaea0sDABZGE9wocPwBYam5ilJial0MDCPBYgydAApIB2zodY-rYabKmJpamZRWoizSxdALF0P8TSF1fBlqZYGBgYpSbRzNIDEEvvQyx9ehliqUmyqaWRGc0sfQCxFBqnj7shwWtumJiUbECcYVkABNIoEQ ] `

Investigtion  on cloudant DB server side showed that the  HTTP reqeust for   SeqNr:  1520029-  did not reached server. 

```
Dec 18 12:06:14 lb2.bm-whisk012 haproxy[26686]: 128.168.73.83:36817 -> since=1520027-g1AAAAObe
Dec 18 12:06:15 lb2.bm-whisk012 haproxy[26686]: 128.168.73.83:36817 -> since=1520028-g1AAAAObe
```
Question:  Is there a known  or possible error case in the  postChanges() call that is suppressing the timeout

**Comment by padamstx** [comment]
This repository is a container for documentation that is common to IBM Cloud client SDKs produced with the IBM Cloud SDK Generator.

This issue seems like you are encountering an issue with a specific service and/or operation.  Please open an issue against the specific SDK that you are using.

**Comment by groezing** [comment]
Sorry, wrong repo
