### ISSUE TITLE
`set_disable_ssl_verification` not applying

### ISSUE THREAD

**Issue by ion-elgreco** [IBM/ibm-cloud-sdk-common#50]
I have `set_disable_ssl_verification `to `True`. However, it's not applying, it is still mentioning that the SSL certificate can't be found. Manually changing the request.session settings disables it properly. 

Am I missing something here?

**Comment by ion-elgreco** [comment]
Wrong repo : )

**Comment by nrocaalh** [comment]
Hi,
I'm having the same issue, which is the correct repo to chceck it?
Thank you,

**Comment by padamstx** [comment]
The python sdk core repo (https://github.com/IBM/python-sdk-core) is probably the right place to report this, but before opening an issue, please make sure you are following the instructions located here: https://github.com/IBM/ibm-cloud-sdk-common/blob/main/README.md#programmatically-1 (see the example in the Python section).
